<h2>Group using this form</h2>

<?php echo Phalcon\Tag::form(array('group/getGroup','method'=>'get')) ?>
	
	<p>
		<label for="name">Name</label>
		<?php echo Phalcon\Tag::textField("gname") ?>
	</p>

	<p>
		<?php echo Phalcon\Tag::submitButton("getGroup") ?>
	</p>

</form>

<?php echo Phalcon\Tag::form(array('group/addGroup','method'=>'post')) ?>
	
	<p>
		<label for="name">Name</label>
		<?php echo Phalcon\Tag::textField("gname") ?>
	</p>

	<p>
		<?php echo Phalcon\Tag::submitButton("addGroup") ?>
	</p>

</form>

<?php echo Phalcon\Tag::form(array('group/addUserGroup','method'=>'post')) ?>
	
	<p>
		<label for="name">GID</label>
		<?php echo Phalcon\Tag::textField("gid") ?>
	</p>
	<p>
		<label for="name">UID</label>
		<?php echo Phalcon\Tag::textField("uid") ?>
	</p>

	<p>
		<?php echo Phalcon\Tag::submitButton("addUserGroup") ?>
	</p>

</form>
